### ISSUE TITLE
Rechtschreibfehler: than

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/responses#4]
An vielen Stellen im Code wird statt "than" "then" verwendet. Das ist grammatikalisch falsch und muss korrigiert werden. Z.B. hier: https://github.com/iqb-berlin/responses/blob/df04c3ad3ea043cf433251842389685290d8bba1/json_schema/coding-scheme/coding-scheme.json#L143

**Comment by jurei733** [comment]
Fixed
