### ISSUE TITLE
newResponse.state statt newResponse.status in NPM Paket

### ISSUE THREAD

**Issue by ojauch** [iqb-berlin/responses#5]
In dem hier veröffentlichten NPM Paket (https://www.npmjs.com/package/@iqb/responses) wird in der Klasse `CodingScheme` in der Methode `code(unitResponses)` `newResponse.state` statt wie in der Typescript Datei `newResponse.status` aufgerufen. Außerdem wird das Paket bei NPM als deprecated gelistet. Ist dies beabsichtigt und wenn ja was sollte alternativ genutzt werden?

**Comment by jurei733** [comment]
Das aktuelle Paket ist 1.1.3 mit newResponse.status.
