### ISSUE TITLE
Kodierfehler bei Optionsfeldern

### ISSUE THREAD

**Issue by ojauch** [iqb-berlin/responses#6]
Bei der Kodierung von Antworten zu Optionsfeldern wird die Antwort, auch wenn das richtige Feld ausgewählt wurde, als falsch kodiert.

Getestet mit:

Player: Aspect Player 2.4.10

Editor: Aspect Editor 2.4.9

Schemer: IQB Schemer 1.5.0

Das Kodierschema wurde mit der "Kodierung generieren" Funktion erstellt

Input:

```json
{
    "id": "radio_1",
    "value": 1,
    "status": "VALUE_CHANGED"
}
```

Output:

```json
{
    "id": "radio_1",
    "value": 1,
    "status": "CODING_COMPLETE",
    "code": 2,
    "score": 0
}
```

Aufgabe: 
[test-aufgabe.voud.json](https://github.com/iqb-berlin/responses/files/15089653/test-aufgabe.voud.json) (json Dateiendung nur hinzugefügt, um bei Github hochzuladen)

Kodierschema: 
[test-aufgabe.vocs.json](https://github.com/iqb-berlin/responses/files/15089663/test-aufgabe.vocs.json)

**Comment by jurei733** [comment]
Die Aufgabe bitte komplett als zip exportieren und hier hochladen.

**Comment by ojauch** [comment]
[2024-04-24 studio unit download.zip](https://github.com/iqb-berlin/responses/files/15104798/2024-04-24.studio.unit.download.zip)

**Comment by jurei733** [comment]
Mit dem Kodiermodell "Ankreuzen/Auswählen" lässt sich aktuell keine fehlerfreie Kodierung erzeugen wenn man sich die Kodierung generieren lässt. Kurzfristig lässt sich diesselbe Kodierung der Aufgabe  ohne Kodiermodell und ohne "Generierung der Kodierung" erstellen und dann funktioniert es.
